In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/NeilPandey/Test_Dataset/master/car.data",names=['buying','maint','doors','persons','lug_boot','safety','class'])
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [3]:
df.shape

(1728, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 47.3+ KB


In [5]:
df['class'],class_names=pd.factorize(df['class'])

In [6]:
print(class_names)

Index(['unacc', 'acc', 'vgood', 'good'], dtype='object')


In [7]:
print(df['class'].unique())

[0 1 2 3]


In [8]:
df['buying'],class_names=pd.factorize(df['buying'])
df['maint'],class_names=pd.factorize(df['maint'])
df['doors'],class_names=pd.factorize(df['doors'])
df['persons'],class_names=pd.factorize(df['persons'])
df['lug_boot'],class_names=pd.factorize(df['lug_boot'])
df['safety'],class_names=pd.factorize(df['safety'])

In [9]:
df.head(10)

buying  maint  doors  persons  lug_boot  safety  class
0       0      0      0        0         0       0      0
1       0      0      0        0         0       1      0
2       0      0      0        0         0       2      0
3       0      0      0        0         1       0      0
4       0      0      0        0         1       1      0
5       0      0      0        0         1       2      0
6       0      0      0        0         2       0      0
7       0      0      0        0         2       1      0
8       0      0      0        0         2       2      0
9       0      0      0        1         0       0      0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   int32
 1   maint     1728 non-null   int32
 2   doors     1728 non-null   int32
 3   persons   1728 non-null   int32
 4   lug_boot  1728 non-null   int32
 5   safety    1728 non-null   int32
 6   class     1728 non-null   int32
dtypes: int32(7)
memory usage: 47.3 KB


In [11]:
#data prep
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [13]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [14]:
y_pred = classifier.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[397   2   0   0]
 [  6 116   0   4]
 [  0   1  18   0]
 [  0   1   0  26]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       399
           1       0.97      0.92      0.94       126
           2       1.00      0.95      0.97        19
           3       0.87      0.96      0.91        27

    accuracy                           0.98       571
   macro avg       0.95      0.96      0.95       571
weighted avg       0.98      0.98      0.98       571

